project:
  type: book
  output-dir: docs

website:
  favicon: img/hex-shiny.png
  twitter-card:
    creator: "@wamorim_"
    site: "@curso_r"

book:
  title: "Programando em Shiny"
  date: today
  repo-url: https://github.com/curso-r/programando-em-shiny/
  downloads: [pdf, epub]
  repo-actions: [edit, issue]
  sharing: [twitter, facebook]
  page-footer: |
    Escrito por [William Amorim](https://twitter.com/wamorim_) e mantido pela equipe da [Curso-R](https://curso-r.com/).
  chapters:
    - index.qmd
    - sobre.qmd

    - part: Parte 1
      chapters:
        - primeiro-app.qmd
        - add-interatividade.qmd
        - reatividade-conceitos.qmd
        - debug.qmd
        - layouts.qmd
        - shiny-na-pratica-1.qmd
        - reatividade-mais-pecas.qmd
        - htmlwidgets.qmd
        - deploy.qmd
    - part: Parte 2
      chapters:
        - modulos.qmd
        - golem.qmd
        - html-css-js.qmd
        - shiny-na-pratica-2.qmd
        - reatividade-problemas-complexos.qmd
    - referencias.qmd

format:
  html:
    css: style.css
    lang: pt
    theme:
      light: cosmo
      dark: darkly
  #pdf:
    # lang: pt
    #documentclass: scrreprt

