project:
  type: book

book:
  title: "Programando em Shiny"
  date: "2022/09/26"
  chapters:
    - index.qmd
    - sobre.qmd

    - part: Parte 1
      chapters:
        - primeiro-app.qmd
        - add-reatividade.qmd
        - reatividade-conceitos.qmd
        - debug.qmd
        - layouts.qmd
        - shiny-na-pratica-1.qmd
        - reatividade-mais-pecas.qmd
        - htmlwidgets.qmd
        - deploy.qmd
    - part: Parte 2
      chapters:
        - modulos.qmd
        - golem.qmd
        - html-css-js.qmd
        - shiny-na-pratica-2.qmd
        - reatividade-problemas-complexos.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: scrreprt

